// <auto-generated />
using Infrastructure.Contexts.Catalog;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MigrationsCatalog
{
    [DbContext(typeof(CatalogAppContext))]
    [Migration("20250630052248_InitialCreateCatalog")]
    partial class InitialCreateCatalog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.Catalog.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Action"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Adventure"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Comedy"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Drama"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Romance"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Fantasy"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Supernatural"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Horror"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Thriller"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Mystery"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Psychological"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Slice of Life"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Sci-Fi"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Mecha"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Military"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Historical"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Music"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Sports"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Martial Arts"
                        },
                        new
                        {
                            Id = 20,
                            Name = "School Life"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Magic"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Crime"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Detective"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Dementia"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Game"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Survival"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Apocalypse"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Post-Apocalyptic"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Space"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Time Travel"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Isekai"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Reincarnation"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Parallel Worlds"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Demons"
                        },
                        new
                        {
                            Id = 35,
                            Name = "Vampires"
                        },
                        new
                        {
                            Id = 36,
                            Name = "Zombies"
                        },
                        new
                        {
                            Id = 37,
                            Name = "Aliens"
                        },
                        new
                        {
                            Id = 38,
                            Name = "Mythology"
                        },
                        new
                        {
                            Id = 39,
                            Name = "Gods"
                        },
                        new
                        {
                            Id = 40,
                            Name = "Cultivation"
                        },
                        new
                        {
                            Id = 41,
                            Name = "Superpower"
                        },
                        new
                        {
                            Id = 42,
                            Name = "Cyberpunk"
                        },
                        new
                        {
                            Id = 43,
                            Name = "Steampunk"
                        },
                        new
                        {
                            Id = 44,
                            Name = "Political"
                        },
                        new
                        {
                            Id = 45,
                            Name = "Philosophy"
                        },
                        new
                        {
                            Id = 46,
                            Name = "Tragedy"
                        },
                        new
                        {
                            Id = 47,
                            Name = "Dark Fantasy"
                        },
                        new
                        {
                            Id = 48,
                            Name = "High Fantasy"
                        },
                        new
                        {
                            Id = 49,
                            Name = "Urban Fantasy"
                        },
                        new
                        {
                            Id = 50,
                            Name = "Light Novel"
                        },
                        new
                        {
                            Id = 51,
                            Name = "Shounen"
                        },
                        new
                        {
                            Id = 52,
                            Name = "Shoujo"
                        },
                        new
                        {
                            Id = 53,
                            Name = "Seinen"
                        },
                        new
                        {
                            Id = 54,
                            Name = "Josei"
                        },
                        new
                        {
                            Id = 55,
                            Name = "Harem"
                        },
                        new
                        {
                            Id = 56,
                            Name = "Reverse Harem"
                        },
                        new
                        {
                            Id = 57,
                            Name = "Ecchi"
                        },
                        new
                        {
                            Id = 58,
                            Name = "Fanservice"
                        },
                        new
                        {
                            Id = 59,
                            Name = "BL (Boys Love)"
                        },
                        new
                        {
                            Id = 60,
                            Name = "GL (Girls Love)"
                        },
                        new
                        {
                            Id = 61,
                            Name = "LGBTQIA+"
                        },
                        new
                        {
                            Id = 62,
                            Name = "Drama Family"
                        },
                        new
                        {
                            Id = 63,
                            Name = "Friendship"
                        },
                        new
                        {
                            Id = 64,
                            Name = "Revenge"
                        },
                        new
                        {
                            Id = 65,
                            Name = "Anti-Hero"
                        },
                        new
                        {
                            Id = 66,
                            Name = "Healing"
                        },
                        new
                        {
                            Id = 67,
                            Name = "Coming of Age"
                        },
                        new
                        {
                            Id = 68,
                            Name = "Satire"
                        },
                        new
                        {
                            Id = 69,
                            Name = "Parody"
                        },
                        new
                        {
                            Id = 70,
                            Name = "Post-Truth"
                        },
                        new
                        {
                            Id = 71,
                            Name = "Psychological Horror"
                        },
                        new
                        {
                            Id = 72,
                            Name = "Psychological Thriller"
                        },
                        new
                        {
                            Id = 73,
                            Name = "Noir"
                        },
                        new
                        {
                            Id = 74,
                            Name = "Biography"
                        },
                        new
                        {
                            Id = 75,
                            Name = "Documentary"
                        },
                        new
                        {
                            Id = 76,
                            Name = "Experimental"
                        },
                        new
                        {
                            Id = 77,
                            Name = "Abstract"
                        },
                        new
                        {
                            Id = 78,
                            Name = "Virtual Reality"
                        },
                        new
                        {
                            Id = 79,
                            Name = "Augmented Reality"
                        },
                        new
                        {
                            Id = 80,
                            Name = "Artificial Intelligence"
                        },
                        new
                        {
                            Id = 81,
                            Name = "Post-Human"
                        },
                        new
                        {
                            Id = 82,
                            Name = "Meta"
                        },
                        new
                        {
                            Id = 83,
                            Name = "Fourth Wall"
                        },
                        new
                        {
                            Id = 84,
                            Name = "Breaking the Fourth Wall"
                        },
                        new
                        {
                            Id = 85,
                            Name = "Memoir"
                        },
                        new
                        {
                            Id = 86,
                            Name = "Fantasy Comedy"
                        },
                        new
                        {
                            Id = 87,
                            Name = "Fantasy Romance"
                        },
                        new
                        {
                            Id = 88,
                            Name = "Romantic Comedy"
                        },
                        new
                        {
                            Id = 89,
                            Name = "Action Comedy"
                        },
                        new
                        {
                            Id = 90,
                            Name = "Action Romance"
                        },
                        new
                        {
                            Id = 91,
                            Name = "Supernatural Mystery"
                        });
                });

            modelBuilder.Entity("Domain.Models.Catalog.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tags", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
